### ISSUE TITLE
modulejs.run

### ISSUE THREAD

**Issue by dmgr** [lrsjng/modulejs#1]
It would be nice if moduleJS would offer a "modulejs.run" method which will run a code when all required libraries are available, ie:

```
modulejs.run(['jquery', 'graphics/fx'], function() {
  // run this after loading of jquery and graphics/fx
})
```

**Comment by lrsjng** [comment]
@dmgr just use `modulejs.require()` for that..

**Comment by dmgr** [comment]
It doesn't work, because if you have this order of code snippets:

```
  modulejs.require('lib_a', function(lib_a) {
    console.log('using lib_a');
  });

  modulejs.define('lib_a', function() {
    console.log('lib_a loaded');
    return {};
  });
```

You will have a:
Uncaught Error: [modulejs-32] id not defined "lib_a"

**Comment by lrsjng** [comment]
That will not work at all, as `require` expects a single `id` argument only, no callback.

I think the best way to run your code is after all js is loaded, for example:

```js
document.addEventListener('DOMContentLoaded', function () {

    var app = modulejs.require('main');
    app.start();
});
```

or with jQuery:

```js
jQuery(function () {

    var app = modulejs.require('main');
    app.start();
});
```

but I understand your request now..

**Comment by dmgr** [comment]
Yes, I thought about that solution and I think it will be done using that workaround.
